[package]
name = "pseudo-term"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
nix = { version = "0.30.1", features = [
  "term",
  "socket",
  "uio",
  "aio",
  "fs",
  "ioctl",
  "net",
] }
